[project]
name = "dbrowser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kivy[base]>=2.3.1",
    "kivymd==1.2.0",
    "pyjnius>=1.7.0",
    "pyqt6>=6.5.0",
    "pyqt6-webengine>=6.5.0",
]
